### PR TITLE
add support for reading thermo dad data

### PR DESCRIPTION
**Pull request by ethanbass**
Incorporates support to parse thermo DAD data. Closes wkumler/RaMS#10

### CODE REVIEW

**Comment by ethanbass** [comment]
let me know if you want me to try to write some tests or something. not sure how that would work without a file? the files are huge!

**Comment by wkumler** [comment]
This is neat! The code looks good and I like your implementation of it as another thing that can be requested using `grab_what`. I'll see what I can do to hack together a file for unit tests because I think this is important data to access and having unit tests will ensure that the functionality doesn't get broken further down the line. Feels similar to the way we're implementing chromatograms in #8. Might be a little while since I'm working on some fieldwork now but it's now on my to-do list. Thanks for writing the code!

**Comment by ethanbass** [comment]
sounds good to me. glad you like the code!

**Comment by wkumler** [comment]
Ok, I've made a "minified" DAD file from one of the files you sent me consisting of the first 5 MS scans and the first 5 DAD scans - that should be enough to run unit tests and ensure later contributions don't break DAD processing. It's also nice that you have both pos and neg mode in those files, that's something I hadn't thought to test for before. Are you ok with this minified file being included in the package?
[20220404_CirA_D5_30_mini.mzML.gz](https://github.com/wkumler/RaMS/files/9956193/20220404_CirA_D5_30_mini.mzML.gz)

**Comment by ethanbass** [comment]
Awesome thanks for doing that! I think it's probably fine. I actually got
the file from Ben Reisman, so I just sent him a message to confirm. Will
let you know when i hear back

**Comment by ethanbass** [comment]
He said it's fine to use the file!

**Comment by wkumler** [comment]
Nice! It's now live in the latest version of the package.

**Pull request merged**
